-- Cartographer 2D configuration - AUTO-GENERATED FOR TUNING
-- DO NOT EDIT - Generated by Optuna hyperparameter tuning
-- Optimized for: 10m x 10m indoor room with featureless walls

include "map_builder.lua"
include "trajectory_builder.lua"

options = {
  map_builder = MAP_BUILDER,
  trajectory_builder = TRAJECTORY_BUILDER,

  -- === Frame Configuration ===
  map_frame = "map",
  tracking_frame = "base_footprint",
  published_frame = "base_footprint",
  odom_frame = "odom",

  provide_odom_frame = false,
  publish_frame_projected_to_2d = true,

  -- === Sensor Configuration ===
  use_odometry = true,
  use_nav_sat = false,
  use_landmarks = false,

  num_laser_scans = 1,
  num_multi_echo_laser_scans = 0,
  num_subdivisions_per_laser_scan = 1,
  num_point_clouds = 0,

  -- === Timing ===
  lookup_transform_timeout_sec = 2.0,
  submap_publish_period_sec = 0.3,
  pose_publish_period_sec = 5e-3,
  trajectory_publish_period_sec = 30e-3,

  -- === Sampling Ratios ===
  rangefinder_sampling_ratio = 1.0,
  odometry_sampling_ratio = 1.0,
  fixed_frame_pose_sampling_ratio = 1.0,
  imu_sampling_ratio = 1.0,
  landmarks_sampling_ratio = 1.0,
}

-- === Map Builder Configuration ===
MAP_BUILDER.use_trajectory_builder_2d = true
MAP_BUILDER.num_background_threads = 4

-- === Trajectory Builder 2D Configuration ===
TRAJECTORY_BUILDER_2D.use_imu_data = false
TRAJECTORY_BUILDER_2D.min_range = 0.1
TRAJECTORY_BUILDER_2D.max_range = 10.0
TRAJECTORY_BUILDER_2D.missing_data_ray_length = 5.0
TRAJECTORY_BUILDER_2D.num_accumulated_range_data = 1
TRAJECTORY_BUILDER_2D.voxel_filter_size = 0.04

-- *** CRITICAL: Online correlative scan matching (TUNED) ***
TRAJECTORY_BUILDER_2D.use_online_correlative_scan_matching = true
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.linear_search_window = 0.151
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.angular_search_window = 0.2453
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.translation_delta_cost_weight = 0.3
TRAJECTORY_BUILDER_2D.real_time_correlative_scan_matcher.rotation_delta_cost_weight = 0.2

-- Motion filter (TUNED) - frequent updates for featureless corridors
TRAJECTORY_BUILDER_2D.motion_filter.max_time_seconds = 0.3
TRAJECTORY_BUILDER_2D.motion_filter.max_distance_meters = 0.055
TRAJECTORY_BUILDER_2D.motion_filter.max_angle_radians = 0.106

-- Submaps (TUNED) - smaller = more loop closure opportunities
TRAJECTORY_BUILDER_2D.submaps.num_range_data = 44
TRAJECTORY_BUILDER_2D.submaps.grid_options_2d.resolution = 0.05

-- Ceres scan matcher (TUNED) - high weights prevent wall-sliding
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.occupied_space_weight = 1.0
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.translation_weight = 107.9
TRAJECTORY_BUILDER_2D.ceres_scan_matcher.rotation_weight = 122.3

-- === Pose Graph Configuration ===
POSE_GRAPH.optimize_every_n_nodes = 23
POSE_GRAPH.optimization_problem.huber_scale = 5e0

-- Constraint builder (TUNED) - strict thresholds for featureless walls
POSE_GRAPH.constraint_builder.min_score = 0.759
POSE_GRAPH.constraint_builder.global_localization_min_score = 0.7
POSE_GRAPH.constraint_builder.sampling_ratio = 0.459
POSE_GRAPH.constraint_builder.max_constraint_distance = 8.0

-- Loop closure weights (TUNED)
POSE_GRAPH.constraint_builder.loop_closure_translation_weight = 28175.9
POSE_GRAPH.constraint_builder.loop_closure_rotation_weight = 454522.7

-- Fast correlative scan matcher for loop closure (TUNED)
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.linear_search_window = 4.8
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.angular_search_window = 0.4266
POSE_GRAPH.constraint_builder.fast_correlative_scan_matcher.branch_and_bound_depth = 8

-- Global optimization weights (TUNED) - trust odometry for corridors
POSE_GRAPH.optimization_problem.odometry_translation_weight = 85259.8
POSE_GRAPH.optimization_problem.odometry_rotation_weight = 38854.0
POSE_GRAPH.optimization_problem.local_slam_pose_translation_weight = 5e4
POSE_GRAPH.optimization_problem.local_slam_pose_rotation_weight = 1e5

return options
